### PR TITLE
Billboard Profit Margins 1.6 compat

### PR DESCRIPTION
**Pull request by akrieger**
Nothing too controversial, I did my best to adapt the old code to the new apis. The special order api changed the most, but it seemed like the logic could be transplanted into an event handler without too much issue. Item delivery quest pricing needed some fixup to handle the event only having an ItemId and not an Item attached, but also not bad.

I didn't validate that the special orders logic actually works because I don't have a save far enough along for that, but item delivery quest price adjustment does work.

Project file was updated with `upgrade-assistant upgrade` https://dotnet.microsoft.com/en-us/platform/upgrade-assistant

### CODE REVIEW

**Comment by desto-git** [comment]
Hello! Thank you very much for your contribution :)

I could build and run it with the new version, and validate that the special orders are adjusted as well. It seems like the story quests aren't handled properly yet, though. But I will look into that myself.

I will update the official mod version in the coming days, along with my other mods. Your work is very useful as a reference and much appreciated. Thanks again :D

**Comment by akrieger** [comment]
For reference, I also had to manually remove the other project references like
```
<PackageReference Include="Microsoft.Net.Compilers" Version="3.3.1">
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    <PrivateAssets>all</PrivateAssets>
</PackageReference>
```

because I was getting compilation errors otherwise. There was some gui/msbuild issue where the warning level could not be lowered from 6, and the earlier compilers only accept warning levels 0 through 4. So the other projects may need the same manual adjustment!

**Comment by desto-git** [comment]
When I opened the project in Visual Studio, it also showed the Compiler as a legacy dependency, and that it may safely be removed, which I did for all projects.

Doing that, it didn't add the `<WarningLevel>` blocks, so I removed them as well, since I didn't see any change to my warning log with or without them.

And by the way, my comment about the story quest was wrong. In that it never worked to begin with 😅 I didn't adjust them because I didn't find a proper event to handle them only once without having to save additional state information in the save file. Also, I think story quests are negligible when it comes to the rewards, so I didn't bother.

Thank you again for your contribution. It was a great help in understanding what had to be changed after the update :)

**Comment by akrieger** [comment]
Oh yeah, sorry, I think I manually added the warning level when trying to work around the legacy compiler issue. I forgot to delete it, glad it didn't seem to make a difference in any case.

**Pull request merged**
